# start Airflow
execute:
	docker compose up airflow-init
	docker compose up

# login to Airflow web UI @ 'localhost:8080' with username='airflow, password='airflow'

# run the DAG

unexecute:
	docker compose down --volumes --rmi all